---
title: "Books"
date: 2018-06-20T13:50:22-07:00
draft: true
slug: books
---

## Books Reading Now

* Into Thin Air - Jon Krakauer
* The Power of Now - Echart Tolle
* Machine Learning yearning - Andrew Ng [Read through chapters 1-10, [source](https://gallery.mailchimp.com/dc3a7ef4d750c0abfc19202a3/files/0d2d4a3b-96ab-4a8e-aa15-9320a70852b8/NG_MLY01_10.pdf)]

## Books Read 

* Rich dad poor dad
* The Alchemist Summary of the Alchemist
* Mens are from Mars, Women are from Venus
* The Fountainhead by Ayn Rand
* For men only, A straightforward guide to the inner lives of women

  * ### May 2018
    * The organized mind
    * Your one word by Evan Carmichael

  * ### June 2018
    * The Outliers by Malcolm Galdwell
    * The 10x Rule by Grant Cardone
    * The Fred Factor by Mark Sanborne
    * The new one Minute Manager by Ken Blanchard and Spencer Johnson
    * Start with why by Simon Sinek
    
## Books to Read

* Everything happens for a reason by Kate Bowler
* Leonardo Da Vinci by Walter Isaacson
* Harry Potter and the Sorceror's stone
* Total Money Makeover by Dave Ramsey
* The Intelligent Investor by Benjamin Graham
* Factfulness by Hans Rosling
* The power of Habit by Charles Duhigg
* Leaders Eat Last by Simon Sinek
* The monk who sold his Ferrari by Robin Sharma
* The gone girl by Gillian Flynn
* Sapiens - A Brief History of Humankind

If you think I should read any particular book, please comment below and let me 
know the book's name and author. 